
repos:
  - repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: '22.6.0'  # Use the sha / tag you want to point at
    hooks:
      - id: black-conda
  - repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: '5.10.1'  # Use the sha / tag you want to point at
    hooks:
      - id: isort-conda