# run: conda env create --file environment.yml
name: autoLabel
channels:
  - defaults
dependencies:
  - python>=3.6
  - numpy
  - pip
  - pip:
    - opencv-python
    - matplotlib
    - scikit-image
    - scikit-learn
    - tqdm
    - pre-commit 
    - black
    - isort
